apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: reservation-service
  namespace: ticketing-reservation
  labels:
    app.kubernetes.io/name: reservation-service
    app.kubernetes.io/part-of: medikong
    medikong.io/traffic-policy: canary-100
spec:
  hosts:
    - reservation-service
    - reservation-service.ticketing-reservation.svc.cluster.local
  gateways:
    - mesh
  http:
    - name: reservation-canary-100
      route:
        - destination:
            host: reservation-service.ticketing-reservation.svc.cluster.local
            subset: v2
          weight: 100
