apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-shared-resources-private-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-24"
spec:
  project: default
  source:
    repoURL: https://github.com/Medikong/gitops.git
    targetRevision: HEAD
    path: platform/kong
  destination:
    server: https://kubernetes.default.svc
    namespace: ticketing-auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
