apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-helm-private-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-31"
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.8.1
      helm:
        releaseName: longhorn
        values: |
          defaultSettings:
            defaultReplicaCount: 1
            createDefaultDiskLabeledNodes: true
            defaultDataPath: /var/lib/longhorn
            storageReservedPercentageForDefaultDisk: 10
            storageMinimalAvailablePercentage: 10
          preUpgradeChecker:
            jobEnabled: false
          persistence:
            defaultClass: false
            defaultClassReplicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: longhorn
        app.kubernetes.io/part-of: medikong
        medikong.io/platform: storage
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
