apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-private-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-18"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 1.24.4
      helm:
        releaseName: tempo
        valueFiles:
          - $values/platform/observability/tempo/values/private-dev.yaml
    - repoURL: https://github.com/Medikong/gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: observability
        app.kubernetes.io/part-of: medikong
        medikong.io/platform: observability
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
