apiVersion: v1
kind: Namespace
metadata:
  name: ticketing-auth
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: ticketing-concert
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: ticketing-reservation
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: ticketing-payment
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: ticketing-ticket
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: ticketing-notification
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: ticketing-dashboard
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: ticketing-messaging
  labels:
    app.kubernetes.io/part-of: medikong
---
apiVersion: v1
kind: Namespace
metadata:
  name: synthetic
  labels:
    app.kubernetes.io/part-of: medikong
