environment: dev

image:
  registry: localhost:5001
  tag: dev
  pullPolicy: Always

deployment:
  replicas: 2

container:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

pdb:
  enabled: false

hpa:
  enabled: false

serviceMonitor:
  enabled: false
