apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-aws-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Medikong/gitops.git
      targetRevision: HEAD
      path: charts/medikong-service
      helm:
        releaseName: payment-aws-dev
        valueFiles:
          - $values/values/base.yaml
          - $values/values/env/aws-dev.yaml
          - $values/values/services/payment.yaml
          - $values/values/services/aws-dev/payment.yaml
    - repoURL: https://github.com/Medikong/gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ticketing-payment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
