apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reservation-aws-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Medikong/gitops.git
      targetRevision: HEAD
      path: charts/medikong-service
      helm:
        releaseName: reservation-aws-dev
        valueFiles:
          - $values/values/base.yaml
          - $values/values/env/aws-dev.yaml
          - $values/values/services/reservation.yaml
          - $values/values/overrides/aws-dev-smoke-stable.yaml
    - repoURL: https://github.com/Medikong/gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ticketing-reservation
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
