{{- if and .Values.reportArchive.enabled (not .Values.reportArchive.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-report-archive" (include "read-api-loadtest.fullname" .) | quote }}
  namespace: {{ include "read-api-loadtest.namespace" . | quote }}
  labels:
{{ include "read-api-loadtest.labels" . | indent 4 }}
spec:
  accessModes:
{{ toYaml .Values.reportArchive.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.reportArchive.size | quote }}
{{- if .Values.reportArchive.storageClassName }}
  storageClassName: {{ .Values.reportArchive.storageClassName | quote }}
{{- end }}
{{- end }}
