{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "read-api-loadtest.serviceAccountName" . | quote }}
  namespace: {{ include "read-api-loadtest.namespace" . | quote }}
  labels:
{{ include "read-api-loadtest.labels" . | indent 4 }}
{{- with .Values.image.pullSecrets }}
imagePullSecrets:
{{- range . }}
  - name: {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
