apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: concert-private-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Medikong/gitops.git
      targetRevision: HEAD
      path: charts/medikong-service
      helm:
        releaseName: concert-private-dev
        valueFiles:
          - $values/values/base.yaml
          - $values/values/env/private-dev.yaml
          - $values/values/services/concert.yaml
          - $values/values/services/private-dev/concert.yaml
          - $values/values/overrides/private-dev-ha-stable.yaml
    - repoURL: https://github.com/Medikong/gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ticketing-concert
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
