apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-private-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://github.com/TicketMong/gitops.git
      targetRevision: HEAD
      path: charts/medikong-service
      helm:
        releaseName: user-private-dev
        valueFiles:
          - $values/values/base.yaml
          - $values/values/env/private-dev.yaml
          - $values/values/services/user.yaml
          - $values/values/services/private-dev/user.yaml
          - $values/values/overrides/private-dev-ha-stable.yaml
    - repoURL: https://github.com/TicketMong/gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ticketing-user
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
