apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 2.26.0
    helm:
      releaseName: kiali-server
      values: |
        auth:
          strategy: anonymous
        deployment:
          accessible_namespaces:
            - "**"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
        external_services:
          prometheus:
            enabled: true
            url: http://kube-prometheus-stack-prometheus.monitoring:9090
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
