environment: local

image:
  registry: localhost:5001
  repository: synthetic-traffic
  tag: dev
  pullPolicy: Always
  pullSecrets: []

cronJob:
  schedule: "* * * * *"

synthetic:
  scenario: external-journey
  target: external
  baseUrl: http://kong-kong-proxy.kong.svc.cluster.local
  internalBaseUrl: http://kong-kong-proxy.kong.svc.cluster.local
  externalBaseUrl: http://kong-kong-proxy.kong.svc.cluster.local
