apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: auth-service-user
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    app.kubernetes.io/part-of: medikong
username: auth-service-user
credentials:
  - auth-service-jwt
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-jwt
  labels:
    konghq.com/credential: jwt
    app.kubernetes.io/part-of: medikong
stringData:
  key: auth-service
  secret: ticketing-dev-secret
  algorithm: HS256
