{{- if and .Values.migration.enabled .Values.migration.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-migration" .Values.app.name) .Values.migration.serviceAccount.name | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ .Values.app.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: migration
    app.kubernetes.io/part-of: medikong
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-2"
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
{{- with .Values.migration.serviceAccount.annotations }}
{{ toYaml . | nindent 4 }}
{{- end }}
automountServiceAccountToken: false
{{- end }}
