apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name | quote }}
  namespace: {{ .Values.app.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/part-of: medikong
{{- with .Values.app.labels }}
{{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app: {{ .Values.app.name | quote }}
  ports:
{{- if .Values.service.ports }}
{{ toYaml .Values.service.ports | nindent 4 }}
{{- else }}
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- end }}
