env:
  database: "off"

replicaCount: 1

deployment:
  daemonset: false

admin:
  enabled: false

manager:
  enabled: false

portal:
  enabled: false

portalapi:
  enabled: false

proxy:
  type: NodePort
  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
    nodePort: 32407
  tls:
    enabled: false

ingressController:
  enabled: true
  ingressClass: kong
  createIngressClass: true
  resources:
    requests:
      cpu: 5m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

resources:
  requests:
    cpu: 5m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 768Mi

postgresql:
  enabled: false
