apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medikong-private-dev-apps
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Medikong/gitops.git
      targetRevision: HEAD
      path: argo/applications/private-dev/platform
    - repoURL: https://github.com/Medikong/gitops.git
      targetRevision: HEAD
      path: argo/applications/private-dev/services
    - repoURL: https://github.com/Medikong/gitops.git
      targetRevision: HEAD
      path: argo/applications/private-dev/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
