apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver-aws-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-31"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    chart: aws-ebs-csi-driver
    targetRevision: 2.61.1
    helm:
      releaseName: aws-ebs-csi-driver
      values: |
        controller:
          region: ap-northeast-2
        defaultStorageClass:
          enabled: false
        helmTester:
          enabled: false
        node:
          enableWindows: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
