apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: read-api-loadtest-aws-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  project: default
  source:
    repoURL: https://github.com/Medikong/gitops.git
    targetRevision: HEAD
    path: platform/loadtest
    helm:
      releaseName: read-api-loadtest
      valueFiles:
        - values/aws-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: loadtest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
